title: Leitlinien zur Publikation einfach nutzbarer Daten
description: Kanton Zürich, Fachausschuss Open Government Data - Status: ENTWURF
markdown: kramdown
# remote_theme: carlosperate/jekyll-theme-rtd
theme: jekyll-theme-cayman

# Theme settings:
site_author: Fach- und Koordinationsstelle Open Government Data, Statistisches Amt Kanton Zürich
repo_url: "https://github.com/openZH/mdd-ogd-handbook"
edit_on_github: true
github_docs_folder: true
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: true
hljs_style: github-gist
