title: Handbuch Metadaten-Diffusion (MDD) und Bereitstellung offener Behördendaten (OGD)
description: Handbuch des Datenkatalogs des Kantons Zürich zur Metadaten-Diffusion (MDD) und Bereitstellung offener Behördendaten (OGD).
markdown: kramdown
# remote_theme: carlosperate/jekyll-theme-rtd
theme: jekyll-theme-cayman

# Theme settings:
site_author: Fach- und Koordinationsstelle OGD
repo_url: "https://github.com/openZH/mdd-ogd-handbook"
edit_on_github: true
github_docs_folder: true
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: true
hljs_style: github-gist
